"""Transforms module.
=====================
Provides light-weight utilities for tensors generated by the Deform_post pipeline (main.py serialize).
"""

import logging
import torch
from typing import Optional
from torchvision import transforms

logger = logging.getLogger(__name__)


def get_transforms(config: dict) -> Optional[transforms.Compose]:
    """
    Return the optional image transform. Data exported by Deform_post already
    arrives as torch.Tensor objects, so we usually keep it unchanged.
    Training, validation, and test stages therefore share the same logic.

    Args:
        config: Configuration values read from the YAML file.

    Returns:
        transforms.Compose | None: Normalization steps when requested, otherwise
        ``None``.
    """
    if config["data"]["augmentation"].get("override_normalization", False):
        normalize_params = config["data"]["augmentation"]["normalize"]
        logger.info("Applying additional normalization transform")
        return transforms.Compose([
            transforms.Normalize(
                mean=normalize_params["mean"],
                std=normalize_params["std"],
            )
        ])

    logger.info("Using preprocessed tensors without additional transforms")
    return None

def denormalize_from_metadata(image_tensor: torch.Tensor, metadata: dict) -> torch.Tensor:
    """Undo normalization using values stored in metadata.

    Args:
        image_tensor: Normalized tensor.
        metadata: Metadata written by the Deform_post pipeline (main.py serialize).

    Returns:
        torch.Tensor: Tensor scaled back to the original range.

    Raises:
        ValueError: Raised when needed fields are missing.
    """
    if not metadata.get('normalize_images', False):
        return image_tensor

    if 'image_mean' not in metadata or 'image_std' not in metadata:
        raise ValueError(
            "Metadata is missing required normalization parameters "
            "'image_mean' or 'image_std'. Cannot perform "
            "denormalization without complete metadata."
        )
    mean = torch.tensor(metadata['image_mean'])
    std = torch.tensor(metadata['image_std'])
    # Match tensor shape for either single images or batched input.
    if image_tensor.dim() == 3:  # (C, H, W)
        mean = mean.view(3, 1, 1)
        std = std.view(3, 1, 1)
    elif image_tensor.dim() == 4:  # (B, C, H, W)
        mean = mean.view(1, 3, 1, 1)
        std = std.view(1, 3, 1, 1)
    else:
        raise ValueError(
            f"Unsupported image_tensor.dim()={image_tensor.dim()}, expected 3 or 4."
        )

    return image_tensor * std + mean
