"""Transforms module.
=====================
Provides light-weight utilities for tensors generated by the Deform_post pipeline (main.py serialize).

Phase-0 measurement fix: optional, config-gated, TRAIN-ONLY photometric
augmentation. It is LABEL-SAFE BY CONSTRUCTION -- only pixel-value operations
(brightness/contrast/saturation/hue jitter, blur, gamma, gaussian noise), and
NEVER geometric ones (flip/crop/rotate/affine), because any geometric change
would rotate the 3D force-vector label. It is disabled unless
``data.augmentation.photometric.enabled`` is true, so the default behavior is
unchanged. Augmentation is applied to TRAINING data only; val/test stay clean.

Config schema (under ``data.augmentation``)::

    photometric:
      enabled: false          # master switch; train-only
      p: 0.8                  # prob of applying colour jitter
      brightness: 0.3
      contrast: 0.3
      saturation: 0.3
      hue: 0.05
      blur_p: 0.2             # prob of gaussian blur
      blur_sigma: [0.1, 1.5]
      gamma: [0.8, 1.2]       # random gamma range (1.0 == identity)
      noise_std: 0.02         # additive gaussian noise std (0 disables)
"""

import logging
import random
from typing import Optional

import torch
from torchvision import transforms
from torchvision.transforms import ColorJitter, GaussianBlur

logger = logging.getLogger(__name__)


class PhotometricAugment:
    """Train-only, LABEL-SAFE photometric augmentation for [0, 1] CHW images.

    Operates purely on pixel values (no spatial/geometric change), so the 3D
    force-vector label is preserved by construction. Casts to float32 internally
    for the torchvision ops, then restores the input dtype (the cache may store
    bfloat16).
    """

    def __init__(self, cfg: dict) -> None:
        self.p = float(cfg.get("p", 0.8))
        self._jitter = ColorJitter(
            brightness=float(cfg.get("brightness", 0.3)),
            contrast=float(cfg.get("contrast", 0.3)),
            saturation=float(cfg.get("saturation", 0.3)),
            hue=float(cfg.get("hue", 0.05)),
        )
        self.blur_p = float(cfg.get("blur_p", 0.2))
        sigma = cfg.get("blur_sigma", [0.1, 1.5])
        self._blur = GaussianBlur(
            kernel_size=5, sigma=(float(sigma[0]), float(sigma[1]))
        )
        gamma = cfg.get("gamma", [0.8, 1.2])
        self.gamma_lo, self.gamma_hi = float(gamma[0]), float(gamma[1])
        self.noise_std = float(cfg.get("noise_std", 0.02))

    def __call__(self, image: torch.Tensor) -> torch.Tensor:
        orig_dtype = image.dtype
        img = image.float().clamp(0.0, 1.0)
        if self.p > 0 and random.random() < self.p:
            img = self._jitter(img).clamp(0.0, 1.0)
        if self.blur_p > 0 and random.random() < self.blur_p:
            img = self._blur(img)
        if not (self.gamma_lo == 1.0 and self.gamma_hi == 1.0):
            g = random.uniform(self.gamma_lo, self.gamma_hi)
            img = img.clamp(min=0.0).pow(g)
        if self.noise_std > 0:
            img = img + torch.randn_like(img) * self.noise_std
        img = img.clamp(0.0, 1.0)
        return img.to(orig_dtype)


def _photometric_cfg(config: dict) -> Optional[dict]:
    """Return the photometric-augmentation sub-config if enabled, else None."""
    aug = config.get("data", {}).get("augmentation", {}) or {}
    pcfg = aug.get("photometric") or {}
    if pcfg.get("enabled", False):
        return pcfg
    return None


def get_transforms(config: dict, train: bool = False) -> Optional[transforms.Compose]:
    """
    Return the optional image transform chain.

    Data exported by Deform_post already arrives as torch.Tensor objects. We
    optionally apply (TRAIN ONLY) LABEL-SAFE photometric augmentation, then
    optionally normalize (ImageNet stats). val/test never get augmentation, so
    passing ``train=False`` reproduces the historical behavior exactly.

    Args:
        config: Configuration values read from the YAML file.
        train: When True, prepend photometric augmentation if it is enabled in
            ``data.augmentation.photometric``.

    Returns:
        transforms.Compose | None: The transform chain, or ``None`` when nothing
        is requested.
    """
    steps = []

    pcfg = _photometric_cfg(config) if train else None
    if pcfg is not None:
        steps.append(PhotometricAugment(pcfg))
        logger.info("Applying TRAIN-ONLY label-safe photometric augmentation")

    if config["data"]["augmentation"].get("override_normalization", False):
        normalize_params = config["data"]["augmentation"]["normalize"]
        logger.info("Applying additional normalization transform")
        steps.append(
            transforms.Normalize(
                mean=normalize_params["mean"],
                std=normalize_params["std"],
            )
        )

    if not steps:
        logger.info("Using preprocessed tensors without additional transforms")
        return None
    return transforms.Compose(steps)


def denormalize_from_metadata(image_tensor: torch.Tensor, metadata: dict) -> torch.Tensor:
    """Undo normalization using values stored in metadata.

    Args:
        image_tensor: Normalized tensor.
        metadata: Metadata written by the Deform_post pipeline (main.py serialize).

    Returns:
        torch.Tensor: Tensor scaled back to the original range.

    Raises:
        ValueError: Raised when needed fields are missing.
    """
    if not metadata.get('normalize_images', False):
        return image_tensor

    if 'image_mean' not in metadata or 'image_std' not in metadata:
        raise ValueError(
            "Metadata is missing required normalization parameters "
            "'image_mean' or 'image_std'. Cannot perform "
            "denormalization without complete metadata."
        )
    mean = torch.tensor(metadata['image_mean'])
    std = torch.tensor(metadata['image_std'])
    # Match tensor shape for either single images or batched input.
    if image_tensor.dim() == 3:  # (C, H, W)
        mean = mean.view(3, 1, 1)
        std = std.view(3, 1, 1)
    elif image_tensor.dim() == 4:  # (B, C, H, W)
        mean = mean.view(1, 3, 1, 1)
        std = std.view(1, 3, 1, 1)
    else:
        raise ValueError(
            f"Unsupported image_tensor.dim()={image_tensor.dim()}, expected 3 or 4."
        )

    return image_tensor * std + mean
