#include "stdafx.h"
#include "bmgl.h"

// GLSL parameters
GLuint frb, rrb;
GLuint vertShader;
GLuint fragShader;
GLuint gl2Program;

// Texture paramters
GLuint ntex[TEXTURE_NUM];

PFNGLTEXIMAGE3DEXTPROC glTexImage3DEXT;
PFNGLACTIVETEXTUREPROC glActiveTexture;
PFNGLACTIVETEXTUREARBPROC glActiveTextureARB;
PFNGLGENFRAMEBUFFERSEXTPROC glGenFramebuffersEXT;
PFNGLBINDFRAMEBUFFEREXTPROC glBindFramebufferEXT;
PFNGLFRAMEBUFFERTEXTURE3DEXTPROC glFramebufferTexture3DEXT;
PFNGLFRAMEBUFFERTEXTURE2DEXTPROC glFramebufferTexture2DEXT;
PFNGLGENRENDERBUFFERSEXTPROC glGenRenderbuffersEXT;
PFNGLBINDRENDERBUFFEREXTPROC glBindRenderbufferEXT;
PFNGLRENDERBUFFERSTORAGEEXTPROC glRenderbufferStorageEXT;
PFNGLFRAMEBUFFERRENDERBUFFEREXTPROC glFramebufferRenderbufferEXT;

